doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # The server version is configured in the DATABASE_URL env var (see .env).

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
        types:
            notification_id: App\NotificationPublisher\Infrastructure\Persistence\Doctrine\Type\NotificationIdType
            delivery_id: App\NotificationPublisher\Infrastructure\Persistence\Doctrine\Type\DeliveryIdType
            delivery_attempt_id: App\NotificationPublisher\Infrastructure\Persistence\Doctrine\Type\DeliveryAttemptIdType
            user_id: App\NotificationPublisher\Infrastructure\Persistence\Doctrine\Type\UserIdType
            idempotency_key: App\NotificationPublisher\Infrastructure\Persistence\Doctrine\Type\IdempotencyKeyType
            recipient: App\NotificationPublisher\Infrastructure\Persistence\Doctrine\Type\RecipientType
    orm:
        enable_lazy_ghost_objects: true
        enable_native_lazy_objects: true
        report_fields_where_declared: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            NotificationPublisher:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/NotificationPublisher/Domain/Model'
                prefix: 'App\NotificationPublisher\Domain\Model'
                alias: NotificationPublisher
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
