; Xdebug is installed but disabled by default.
; Enable it by starting the stack with XDEBUG_MODE=debug docker compose up -d
; See https://xdebug.org/docs/all_settings#mode
xdebug.client_host = 'host.docker.internal'
xdebug.start_with_request = trigger
